### ISSUE TITLE
Detect failed downloads

### ISSUE THREAD

**Issue by MattLish** [RingComics/azuras-star#11]
**Feature**:

Currently, if a download fails, it'll just continue the process anyway without any error/warning which could lead to the rest of the process being invalid.

Suggestions: 
- Make a call to `https://api.nexusmods.com/v1/users/validate.json` to validate the API Key (preventing 401 errors), ask for key again if it fails
- Automatically retry failed downloads (for poor internet connections)
- If it continues to fail, allow manual download with a continue button (possibly a v2 idea)

Implementation thoughts:

It might be worth putting these downloads into an array that includes a link and a set of post download instructions. Then we just loop the array, perform each download and each post download instruction. This would make adding new downloads easy and helps to prepare for working with multiple modpacks that have different downloads.

@RingComics What do you think?

**Comment by RingComics** [comment]
We definitely need a way to tell if downloads completed successfully, and running them asynchronously would be ideal. There is a WinForms object that can show a progress bar, which would help show the user the app hasnt just crashed.
I do eventually plan on adding something similar to the downloads array you mentioned. I'm working with metherul to add manual download instructions to his .auto files, along with modpack configs.

**Comment by RingComics** [comment]
Merged this issue with #32 for the Electron port.
