### ISSUE TITLE
Shortcut requires being run as an admin

### ISSUE THREAD

**Issue by MattLish** [RingComics/azuras-star#16]
To get the shortcut to work, I had to run it as an admin.
Without it, the mods don't loads but there is no error output.

I doubt this is something PS can set for us?

If not, it should probably be added to the final popup.

**Comment by RingComics** [comment]
I found a SO question [here](https://stackoverflow.com/questions/28997799/how-to-create-a-run-as-administrator-shortcut-using-powershell) that did not work in my testing. I'll continue to do some research. I haven't had any problems with it, but if you are, someone else is bound to have issues as well.
