### ISSUE TITLE
Template save only works with Keyboard version, Gamepad template save needs to be created.

### ISSUE THREAD

**Issue by RingComics** [RingComics/azuras-star#17]

**Comment by MattLish** [comment]
Is this necessary?
Aren't all gamepad settings done on post-install?
(I've been playing off your template save for a week with a gamepad and not run into any issues)

**Comment by RingComics** [comment]
You are correct, gamepad not working was a user error on my part! I still need to make a new template save, as there are some mistakes in the MCM that need to be fixed. Closing

**Comment by MattLish** [comment]
@RingComics As a separate personal thing, I'd be interested what these are because I am currently using that template save for a playthrough...
