### ISSUE TITLE
Problem when multiple versions of Skyrim are installed.

### ISSUE THREAD

**Issue by RingComics** [RingComics/azuras-star#18]
I blame Bethesda for this one. Azura takes the install path from the registry and this causes issues if multiple versions (SSE or VR) are installed. Need to implement a dropdown to choose an installation

**Comment by MattLish** [comment]
I think as part of this, it would also make sense to provide an input box for users to fill in their own installation paths if the system can't find one (BB reported that it couldn't find it on an external SSD, which makes sense)

**Comment by MattLish** [comment]
I can pick this up, I made a start on it and I think we can tidy up the Skyrim checking into a class.

**Comment by MattLish** [comment]
@RingComics this is on the assumption that Bethesda assign the same DisplayName for all 3 versions of Skyrim?

**Comment by RingComics** [comment]
I was mostly joking when I said that it was Bethesda's fault, I have no idea what is causing the issue. I have three different versions of Skyrim installed on my PC across two drives (one install is an LE duplicate) and I do not have this issue. 
![skyrim reg](https://user-images.githubusercontent.com/31079038/72977046-7ff79500-3d88-11ea-8499-be15237dda9e.PNG)
You can see in the screenshot that the same line found in the Skyrim check in Azura (slightly altered to find ALL Skyrim installs) correctly identifies the LE version installed through Steam and NOT my copied duplicate, and also finds SSE as a seperate install, which is on a seperate drive. So it's not an issue with Bethesda and/or Steam's registry entries, it seems to be machine specific. I think the best way to mitigate it is to have a pop-up asking the user to select from a list of detected installs and give them the option to browse for another. We would need to check for TESV.exe/SkyrimSE.exe to make sure its an actual Skyrim install folder.
The reason I didn't implement this was to prevent the tool being used on non-Steam / pirated copies of the game but the problems this causes isn't worth the moral dilemma.

**Comment by MattLish** [comment]
So, do you believe the issue is that the command is picking up an array of Skyrim installs rather than just one? Because that's the assumption I worked off and displayed them in a dropdown.

**Comment by RingComics** [comment]
Maybe. I'll be working with BB to see what the specifics of the issues are. Next update I'll be implementing some verbose logging features so we can better troubleshoot user problems

**Comment by MattLish** [comment]
Did some stuff related to this in #19. Might not be related but it'll allow us to break the code apart more easily and likely allow for more verbose logging.

**Comment by RingComics** [comment]
It appears this was fixed in #19. Closing.
