### ISSUE TITLE
No Skyrim Installation results in Required Force Quit

### ISSUE THREAD

**Issue by Alan-Foster** [RingComics/azuras-star#25]
When first installing AS 1.2.0, if you do not have any version of Skyrim installed, it will ask you to identify the folder path with error "Not a valid Skyrim LE install path, please ensure that you have selected the root folder that has TES5.exe" and provide the input box.

If the box is exited, it will show the above error message again, creating a loop with no way to close the program.  Only solution is a command prompt exit.

**Comment by MattLish** [comment]
Good catch!
