### ISSUE TITLE
No installation path for mods outside Skyrim folder

### ISSUE THREAD

**Issue by Alan-Foster** [RingComics/azuras-star#26]
Occasionally, players keep their zipped mod folder separate from their Skyrim folder or in a different directory.  Being able to select the location of this folder would be extremely beneficial for players who already have 90% of the mods downloaded.

**Comment by MattLish** [comment]
@Alan-Foster I agree with this. In fact, this is actually what I do for testing, I just copy the files across when I need them there.
I agree it would be nice to just select a pre-existing folder.

**Comment by RingComics** [comment]
I'll make sure this is added to the Electron port, I plan on giving users far more control over where things are installed instead of following so closely to how I do it.
