### ISSUE TITLE
Automatically download all mods from Nexus

### ISSUE THREAD

**Issue by MattLish** [RingComics/azuras-star#4]
**Feature suggestion**: Automatically download all Nexus mods using the Nexus API.

Personal keys can be found here https://www.nexusmods.com/users/myaccount?tab=api%20access

Things to consider:

- Requires a premium account - maybe there could be an option to enter a key or manually download instead?
- Nexus does have an SSO (that automaton uses) but the app needs to be verified, maybe you could do that? Info [here](https://www.nexusmods.com/site/news/13921)

**Comment by MattLish** [comment]
I have this mostly working on my machine, I just need to add some inputs for keys. Perhaps the option to manually download too.

**Comment by RingComics** [comment]
Definitely want to implement this, I'll take a look at your fork and the documentation you linked and get back to you when I can. thanks for the help!

**Comment by RingComics** [comment]
Just took a look at the Nexus API documentation, looks like everything is good but I dont have a ton of experience with web APIs so I'll do some more research

**Comment by MattLish** [comment]
Don't worry, I'm a web developer so I have plenty of experience so I'm happy to do this. :)

For now, if you can't get the app verified I can always add a link to where a user can find and enter their key.

**Comment by RingComics** [comment]
Next step is getting the app verified. I'd rather not have the user provide their API key, for security reasons more than convenience. If we can't get it verified, we should look into saving the API key as a Secure String

**Comment by MattLish** [comment]
Hopefully the verification is easy enough. If so, I can have a go at the SSO.

**Comment by RingComics** [comment]
Automatic Nexus Downloads confirmed working! #10 has been opened for verification with Nexus.
