### ISSUE TITLE
Supported games

### ISSUE THREAD

**Issue by RingComics** [RingComics/azuras-star#41]
If you want a new game supported, comment on this issue, do not open a new one, it will be removed and ignored.
### Currently supported games
- The Elder Scrolls III: Morrowind
- The Elder Scrolls IV: Oblivion
- The Elder Scrolls V: Skyrim (Legendary Edition)
- The Elder Scrolls V: Skyrim (Special Edition)
- The Elder Scrolls V: Skyrim VR
- Fallout 3
- Fallout NV
- Fallout 4
- Fallout 4 VR

### Planned games to support
This list is prioritized by whether or not Wabbajack has support and an active list for the game, and is otherwise arbitrary.
- Enderal
- Stardew Valley
- Darkest Dungeon
- Dishonored
- The Witcher 3

**Comment by thomasblasquez** [comment]
Individual game support will be made into new issues as demand requires
