### ISSUE TITLE
Wabbajack Lists Mega-issue

### ISSUE THREAD

**Issue by RingComics** [RingComics/azuras-star#44]
If you're having issues with a Wabbajack list, post it here, and I'll add it to the list of known issues once it's confirmed.

## The Elder Scrolls III: Morrowind
Due to the way modding TES3 works, Azura's Star cannot keep your Morrowind game install clean after running a Morrowind modlist, since MCP irrevocably changes the game EXE, and replacing it with the original would require you to rerun MCP everytime you launch the game. This also goes for MGE, as it replaces game files in the Data folder.

Because of this, AS will allow you to add a Morrowind list, but it will not manage any game folder files. If you have multiple lists for TES3, they may conflict. However, at the moment there is only one Morrowind modlist on Wabbajack, so Wabbajack only users will not need to worry about this.

### Bevilex Graphics
UNTESTED

### Ultimate Skyrim (version 4.0.71)
* No known issues as of 11/18/20

### Enderal My Way
UNTESTED

### Total Visual Overhaul (version 1.2.0)
* No known Issues as of 11/18/20
* Need to test version 1.3.0

### Living Skyrim (version 2.5.2)
* No issues as of 11/18/20
* ~~Launching the game gives the following error from EngineFixes.dll:~~
~~`REL/Relocation.h(617): failed to open file` (reported by kevinsmith121)~~ This issue was fixed in [AS 2.0.1](https://github.com/RingComics/azuras-star/releases/tag/v2.0.1)

### Nice Overall Improvement Requiem
UNTESTED

### Total Skyrim Overhaul
UNTESTED

### Keizaal
UNTESTED

### Relics of Hyrule
UNTESTED

### The Phoenix Flavour
* No issues as of 02/1/21

### Elder Souls
UNTESTED

### Serenity
* No issues as of 11/19/20

### Equanimity
* No issues as of 11/19/20

### Elysium
UNTESTED

### Tales from Northern Lands
UNTESTED

### Unofficial Viva New Vegas
UNTESTED

### One for My Courier
* No issues as of 11/18/20

### Fallout 4 Enhanced Edition (F4EE)
* No issues as of 1/18/21

### Sim Settlements Experience
UNTESTED

### Boston Cream Pie
UNTESTED

### Ghoulout
UNTESTED

### Magnum Opus
UNTESTED

### Welcome to Paradise
UNTESTED

### Ultimate VR Essentials (Skyrim)
UNTESTED

### Fallout VR Essentials (Fallout 4)
UNTESTED

**Comment by thomasblasquez** [comment]
This issue is severely outdated and will be closed. Problems found with Wabbajack lists can be made into separate issues.
