### ISSUE TITLE
Template save causes CTD

### ISSUE THREAD

**Issue by RingComics** [RingComics/azuras-star#5]
Loading the template save after a successful install causes the game to hang and inevitably crash.

**Comment by MattLish** [comment]
Do you think this could be caused by the issues I faced in #13?
I wasn't even able to start a new game there with a CTD

**Comment by MattLish** [comment]
I just tested your template save and it loads correctly after #14 
I don't think there was anything wrong with the template, I think the installation itself was failing :)

I couldn't get the gamepad to work, however, but I'm guessing you did a keyboard install?
Perhaps 2 templates are needed.

**Comment by RingComics** [comment]
Template save was not the problem, crashes were caused by SKSE and ENB not being installed correctly, as @MattLish mentioned above and fixed in #14. Template save now working as expected
