### ISSUE TITLE
Automatically detect RAM

### ISSUE THREAD

**Issue by MattLish** [RingComics/azuras-star#8]
**Feature Request**

It looks like it should be possible to automatically detect RAM and VRAM.
The inputs should default to these values.

From what I can see on SO, it's possible to get
RAM:
`(systeminfo | Select-String 'Total Physical Memory:').ToString().Split(':')[1].Trim()`
(Though this contains MB on the end and my PowerShell isn't great, though I assume that can be removed)

VRAM: `Get-WmiObject Win32_VideoController | select AdapterRAM, @{ Expression = { $_.adapterram/1MB }; label = "MB" }`
(This returns it in a form like `@{AdapterRAM=4293918720; MB=4095}`, again, if my PS was better I could probably manipulate that to give just the MB)

What do you think?

**Comment by MattLish** [comment]
On second thought, I have 8GB of VRAM so maybe that number is incorrect...

Still, I think the idea is still worth doing, one less input to do wrong.

**Comment by RingComics** [comment]
I was actually originally doing this, but Powershell does not correctly give the RAM and VRAM values for some reason. Unless I can find another work around, this is currently the best option

**Comment by RingComics** [comment]
Using GPU-Z, I found a way to get VRAM, making this totally possible!

**Comment by MattLish** [comment]
Tested, works great. Good work!
