### ISSUE TITLE
Memory leak caused by Automaton check

### ISSUE THREAD

**Issue by RingComics** [RingComics/azuras-star#9]
Due to some lazy code, the while() loop at line 428 is causing a memory leak. Will replace it with a Wait-Process line, as well as any other areas that use the same technique

**Comment by RingComics** [comment]
Fixed with -Wait arguments after Start-Process calls

**Comment by MattLish** [comment]
Looks good, I'll give it a test

**Comment by MattLish** [comment]
Tested, can confirm this is working :)
